- name: Copy files from backend
  become: true
  copy:
    src: /home/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Start PM2
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
